### ISSUE TITLE
Live Link not working

### ISSUE THREAD

**Issue by yashPundhir** [ANKUSH-meshram/FullStack-JavaScript-BootCamp-2.0#1]
Hi Bro
the link which u have used in your readme file to go to your live project is not working.
please update it.

**Comment by ANKUSH-meshram** [comment]
Which link can please specify the name of project to me

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Yash Pundhir ***@***.***>
Sent: Sunday, December 18, 2022 7:49:59 PM
To: ANKUSH-meshram/FullStack-JavaScript-BootCamp-2.0 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ANKUSH-meshram/FullStack-JavaScript-BootCamp-2.0] Live Link not working (Issue #1)


Hi Bro
the link which u have used in your readme file to go to your live project is not working.
please update it.

**Comment by ANKUSH-meshram** [comment]
Thank you 💙 for your feedback bruhh...1
Got the bug and fixed it one.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ANKUSH-meshram** [comment]
Thank you 💙 for your feedback bruhh...1
Got the bug and fixed it one.
Now the is working fine. You can check it.  Again Thankyou for giving me this valuable feedback.

**Comment by yashPundhir** [comment]
You're welcome buddy.
